"""
Django settings for forward project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

OPTIMIZE_MEDIA = True

ALLOWED_HOSTS_RAW = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip()
                 for host in ALLOWED_HOSTS_RAW.split(',') if host.strip()]

CSRF_TRUSTED_ORIGINS_RAW = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip(
) for origin in CSRF_TRUSTED_ORIGINS_RAW.split(',') if origin.strip()]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_json_widget',
    'core',
    'django_jsonform',
    'martor',
    'rest_framework',
    'corsheaders',
    'api',
    'adminsortable2',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'api.utils.mistakes_were_made',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS_RAW = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip()
                        for origin in CORS_ALLOWED_ORIGINS_RAW.split(',')]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = ['*',
                      'accept',
                      'accept-encoding',
                      'authorization',
                      'content-type',
                      'dnt',
                      'origin',
                      'user-agent',
                      'X-CSRFToken',
                      'x-requested-with',
                      ]

# TODO: Change to true when we have https setup

COOKIE_DOMAIN = os.environ.get("COOKIE_DOMAIN", "forwardapp.org")
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ROOT_URLCONF = 'forward.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forward.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": os.environ.get("DB_NAME", "forward_db"),
        "USER": os.environ.get("DB_USER", "forward_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "forward_password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# Tells Django to use our custom User model instead of the default
AUTH_USER_MODEL = 'core.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sets up the django-storages s3 configuration with minio container

if DEBUG: # uses Minio for development
    print("Development mode active")
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS":{
                "bucket_name": "media-bucket",
                "access_key": "minioadmin",
                "secret_key": "minioadmin",
                "endpoint_url": "http://localhost:9000",
                # "custom_domain": "http://localhost:9000", # test
                # "url_protocol": "http:",
                # "default_acl": "public-read",
                "querystring_auth": True,
                # "use_ssl": False # set to false for local development
            }
        },
        # Required to satisfy django storages but we do not use static files i believe
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }
else: # Production with s3 bucket configuration
    print("Production mode active")
    STORAGES= {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS":{
                "bucket_name": os.getenv("PROD_AWS_MEDIA_BUCKET_NAME"),
                "access_key": os.getenv("PROD_AWS_ACCESS_KEY_ID"),
                "secret_key": os.getenv("PROD_AWS_SECRET_ACCESS_KEY"), 
                "region_name": os.getenv("PROD_AWS_REGION"),
                "use_ssl": True
            }
        },
        # Required to satisfy django storages but we do not use static files i believe
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }


# CMS_COLOR_SCHEME = "light"
MARTOR_ENABLE_LABEL = True

## MARTOR CONFIG
MARTOR_THEME = 'bootstrap'

MARTOR_ENABLE_ADMIN_CSS = False
MARTOR_ALTERNATIVE_CSS_FILE_THEME = 'custom/custom_martor.css'

MARTOR_ENABLE_CONFIGS = {
    # 'emoji': 'true',        # to enable/disable emoji icons.
    'imgur': 'false',        # to enable/disable imgur/custom uploader.
    'mention': 'false',     # to enable/disable mention
    'jquery': 'true',       # to include/revoke jquery (require for admin default django)
    'living': 'true',       # to enable/disable live updates in preview
    'spellcheck': 'false',   # to enable/disable spellcheck in form textareas
    # 'hljs': 'true',         # to enable/disable hljs highlighting in preview
}

MARTOR_TOOLBAR_BUTTONS = [
    'bold', 'italic', 'horizontal', 'heading', 'pre-code',
    'blockquote', 'unordered-list', 'ordered-list',
    'link', 'image-upload',
    # 'underline',
]


MARTOR_MARKDOWNIFY_TIMEOUT = 0

MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',
    'markdown.extensions.sane_lists',

    # Custom markdown extensions.
    'martor.extensions.urlize',
    'martor.extensions.del_ins',      # ~~strikethrough~~ and ++underscores++
    # 'martor.extensions.emoji',        # to parse markdown emoji
]

DJANGO_JSONFORM = {
    'FILE_HANDLER': '/json-file-handler/'
}