# Generated by Django 5.2 on 2025-10-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept Map Concept', 'verbose_name_plural': 'Concept Map Concepts'},
        ),
        migrations.AlterModelOptions(
            name='conceptmap',
            options={'verbose_name': 'Concept Map', 'verbose_name_plural': 'Concept Maps'},
        ),
        migrations.AlterModelOptions(
            name='conceptmapresponse',
            options={'verbose_name': 'Concept Map Response', 'verbose_name_plural': 'Concept Map Responses'},
        ),
        migrations.AlterModelOptions(
            name='dndmatch',
            options={'verbose_name': "Drag N' Drop", 'verbose_name_plural': "Drag N' Drops"},
        ),
        migrations.AlterModelOptions(
            name='dndmatchresponse',
            options={'verbose_name': "Drag N' Drop Response", 'verbose_name_plural': "Drag N' Drop Responses"},
        ),
        migrations.AlterModelOptions(
            name='embed',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Web Embed', 'verbose_name_plural': 'Web Embeds'},
        ),
        migrations.AlterModelOptions(
            name='embedresponse',
            options={'verbose_name': 'Embed Response', 'verbose_name_plural': 'Embed Responses'},
        ),
        migrations.AlterModelOptions(
            name='fillintheblank',
            options={'verbose_name': 'Fill in the Blank', 'verbose_name_plural': 'Fill in the Blanks'},
        ),
        migrations.AlterModelOptions(
            name='fillintheblankresponse',
            options={'verbose_name': 'Fill in the Blank Response', 'verbose_name_plural': 'Fill in the Blank Responses'},
        ),
        migrations.AlterModelOptions(
            name='identification',
            options={'verbose_name': 'Identification', 'verbose_name_plural': 'Identifications'},
        ),
        migrations.AlterModelOptions(
            name='identificationresponse',
            options={'verbose_name': 'Identification Response', 'verbose_name_plural': 'Identification Responses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='likertscale',
            options={'verbose_name': 'Likert Scale', 'verbose_name_plural': 'Likert Scales'},
        ),
        migrations.AlterModelOptions(
            name='likertscaleresponse',
            options={'verbose_name': 'Likert Scale Response', 'verbose_name_plural': 'Likert Scale Responses'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ['order'], 'verbose_name': 'Poll Question', 'verbose_name_plural': 'Poll Questions'},
        ),
        migrations.AlterModelOptions(
            name='pollquestionresponse',
            options={'verbose_name': 'Poll Question Response', 'verbose_name_plural': 'Poll Question Responses'},
        ),
        migrations.AlterModelOptions(
            name='pollresponse',
            options={'verbose_name': 'Poll Response', 'verbose_name_plural': 'Poll Responses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
        migrations.AlterModelOptions(
            name='textcontentresponse',
            options={'verbose_name': 'Text Content Response', 'verbose_name_plural': 'Text Content Responses'},
        ),
        migrations.AlterModelOptions(
            name='twine',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Twine Story', 'verbose_name_plural': 'Twine Stories'},
        ),
        migrations.AlterModelOptions(
            name='twineresponse',
            options={'verbose_name': 'Twine Response', 'verbose_name_plural': 'Twine Responses'},
        ),
        migrations.AlterModelOptions(
            name='userquestionresponse',
            options={'verbose_name': 'Quiz Question Response', 'verbose_name_plural': 'Quiz Question Responses'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterModelOptions(
            name='videoresponse',
            options={'verbose_name': 'Video Response', 'verbose_name_plural': 'Video Responses'},
        ),
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Writing', 'verbose_name_plural': 'Writings'},
        ),
        migrations.AlterModelOptions(
            name='writingresponse',
            options={'verbose_name': 'Writing Response', 'verbose_name_plural': 'Writing Responses'},
        ),
    ]
