# Generated by Django 5.2 on 2025-11-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to accompany the Question', null=True, upload_to='public/question/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional Image to accompany the Quiz', null=True, upload_to='public/quiz/'),
        ),
    ]
