# Generated by Django 5.2 on 2025-10-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=80, help_text='Minimum score required to pass the quiz'),
        ),
    ]
