# Generated by Django 5.2 on 2025-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationitem',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='identificationitem',
            name='image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='identificationitem',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='identificationitem',
            name='image',
            field=models.ImageField(height_field='image_height', help_text='The image below automatically shows\n        percentage values when hovered. If the tooltop at the bottom is not visible, holding still for a bit will show a tooltop\n        with the percentage of the image you are hovered over.', upload_to='public/identification/items/images', width_field='image_width'),
        ),
    ]
