# Generated by Django 5.2 on 2025-12-01 22:00

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
