# Generated by Django 5.2 on 2025-12-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestionresponse',
            name='associated_activity',
        ),
        migrations.RemoveField(
            model_name='pollresponse',
            name='associated_activity',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollquestionresponse',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='pollquestionresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollresponse',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='pollresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollQuestion',
        ),
        migrations.DeleteModel(
            name='PollQuestionResponse',
        ),
        migrations.DeleteModel(
            name='PollResponse',
        ),
    ]
