# Generated by Django 5.2 on 2025-11-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_image_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='image',
            field=models.ImageField(help_text='An image representing the concept.', upload_to='public/concept/'),
        ),
    ]
