# Generated by Django 5.1.6 on 2025-02-20 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the lesson', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(help_text='A detailed description of what the lesson covers')),
                ('objectives', models.JSONField(default=list, help_text='List of learning objectives for this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Optional ordering within a curriculum', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing and searching lessons')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order'], name='core_lesson_order_84bf95_idx')],
            },
        ),
    ]
