# Generated by Django 5.1.6 on 2025-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_identification_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identificationresponse',
            old_name='identification',
            new_name='associated_activity',
        ),
        migrations.RenameField(
            model_name='pollquestionresponse',
            old_name='poll',
            new_name='associated_activity',
        ),
        migrations.RenameField(
            model_name='textcontentresponse',
            old_name='text_content',
            new_name='associated_activity',
        ),
        migrations.RenameField(
            model_name='writingresponse',
            old_name='writing',
            new_name='associated_activity',
        ),
        migrations.AlterField(
            model_name='identificationresponse',
            name='partial_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pollquestionresponse',
            name='partial_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='textcontentresponse',
            name='partial_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='writingresponse',
            name='partial_response',
            field=models.BooleanField(default=True),
        ),
    ]
