# Generated by Django 5.2 on 2025-09-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fillintheblank_fillintheblankresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblankresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fillintheblankresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
    ]
