# Generated by Django 5.2 on 2025-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_concept_options_alter_conceptmap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surveyed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
