# Generated by Django 5.2 on 2025-10-02 00:02

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fillintheblank_fillintheblankresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblankresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fillintheblankresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='attempts_left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='userquizresponse',
            name='id',
        ),
        migrations.RenameField(
            model_name='userquizresponse',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, help_text='the uuid of the database item'),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='associated_activity',
            field=models.ForeignKey(help_text='The quiz this response is for', on_delete=models.deletion.CASCADE, related_name='quiz_responses', to='core.quiz'),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='lesson',
            field=models.ForeignKey(help_text='The lesson related to this response', on_delete=models.deletion.CASCADE, related_name='%(class)s_lesson', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='partial_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquizresponse',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted this response', on_delete=models.deletion.CASCADE, related_name='%(class)s_response_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
