# Generated by Django 5.2 on 2025-10-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_surveyed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surveyed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
