# Generated by Django 5.2 on 2025-08-17 09:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likertscale_likertscaleresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the activity', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('instructions', models.TextField(help_text='Instructions for completing the activity', null=True)),
                ('order', models.PositiveIntegerField(help_text='Order within the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(help_text='List of arrays to match in the format [[drop, drag], ...]')),
                ('lesson', models.ForeignKey(help_text='The lesson this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='core.lesson')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndMatchResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('partial_response', models.BooleanField(default=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('attempts_left', models.PositiveIntegerField(default=0)),
                ('submission', models.JSONField()),
                ('associated_activity', models.ForeignKey(help_text='The DnD match activity associated with this response', on_delete=django.db.models.deletion.CASCADE, related_name='associated_dndmatch', to='core.dndmatch')),
                ('lesson', models.ForeignKey(help_text='The lesson related to this response', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lesson', to='core.lesson')),
                ('user', models.ForeignKey(help_text='The user who submitted this response', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_response_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
