# Generated by Django 5.1.6 on 2025-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_identification_identificationresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationresponse',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
