# Generated by Django 5.1.6 on 2025-02-20 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the section', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('section_type', models.CharField(choices=[('content', 'Content'), ('activity', 'Activity'), ('quiz', 'Quiz')], help_text='The type of section', max_length=50)),
                ('order', models.PositiveIntegerField(help_text='The order in which this section appears in the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='core_sectio_lesson__d01766_idx')],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
