# Generated by Django 5.2 on 2025-12-08 01:23

import django.core.validators
import django.db.models.deletion
import martor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the activity', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('order', models.PositiveIntegerField(help_text='Order of the activity within the lesson. When creating a new activity,<br> this value should be 1 + the number of activities in the lesson found above.')),
                ('instructions', martor.models.MartorField(blank=True, help_text='Instructions for completing the activity', null=True, verbose_name='Instructions')),
                ('instructions_image', models.ImageField(blank=True, height_field='instructions_image_height', help_text='An optional helpful image to display alongside the instructions.', upload_to='public/instructions/', width_field='instructions_image_width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('instructions_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('instructions_image_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Pdf content to acompany lesson', null=True, upload_to='public/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('lesson', models.ForeignKey(help_text='The lesson this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='core.lesson')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('partial_response', models.BooleanField(default=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('attempts_left', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('associated_activity', models.ForeignKey(help_text='The pdf associated with this response', on_delete=django.db.models.deletion.CASCADE, related_name='associated_pdf', to='core.pdf')),
                ('lesson', models.ForeignKey(help_text='The lesson related to this response', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lesson', to='core.lesson')),
                ('user', models.ForeignKey(help_text='The user who submitted this response', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_response_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Response',
                'verbose_name_plural': 'PDF Responses',
            },
        ),
    ]
