# Generated by Django 5.1.6 on 2025-04-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_concept_conceptmap_conceptmapresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='concept_map',
            field=models.ForeignKey(default='53cae5be-2e0c-4958-b8ec-d6d1f371eba4', help_text='The concept map this concept belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.conceptmap'),
            preserve_default=False,
        ),
    ]
