# Generated by Django 5.2 on 2025-12-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdf_pdfresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who reported the bug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
