# Generated by Django 5.2 on 2025-08-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dndmatch_dndmatchresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='image',
            field=models.TextField(blank=True, help_text='Optional image to accompany the text content', null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=models.TextField(blank=True, help_text='The main content text, can include HTML/markdown formatting', null=True),
        ),
    ]
