# Generated by Django 5.1.6 on 2025-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_concept_concept_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
