# Generated by Django 5.2 on 2025-12-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdf_pdfresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
    ]
