# Generated by Django 5.1.6 on 2025-04-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_concept_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='name',
        ),
    ]
