# Generated by Django 5.1.6 on 2025-02-22 03:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_poll_pollquestion_quiz_question_writing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Whether multiple options can be selected'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='options',
            field=models.JSONField(default=[], help_text='Available options for the poll question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='question_text',
            field=models.TextField(default='', help_text='The text of the poll question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='config',
            field=models.JSONField(default=dict, help_text='Configuration options for poll display and behavior'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(help_text='The poll this poll question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='core.poll'),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this content section', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(help_text='The main content text, can include HTML/markdown formatting')),
                ('order', models.PositiveIntegerField(help_text='Order within the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='core.lesson')),
            ],
            options={
                'verbose_name': 'text content',
                'verbose_name_plural': 'text contents',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
