# Generated by Django 5.2 on 2025-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_facility_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='writingresponse',
            name='responses',
            field=models.JSONField(default=list, help_text="The user's written responses in JSON Array format"),
        ),
    ]
