# Generated by Django 4.2.19 on 2025-02-28 19:50

from django.db import migrations

def seed_all_lessons(apps):
    lessons = apps.get_model('core', "Lesson")
    

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_poll_options_alter_pollquestion_options_and_more'),
    ]

    operations = [
    ]
