# Generated by Django 5.2 on 2025-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_writingresponse_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, help_text='Optional image to represent the lesson', max_length=200, null=True),
        ),
    ]
