# Generated by Django 5.1.6 on 2025-03-03 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_poll_options_alter_pollquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False, max_length=1, verbose_name='tracking consent'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Change Display Name', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='display name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='facility_id',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='facility id'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='profile picture link'),
        ),
    ]
