# Generated by Django 5.1.6 on 2025-03-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250228_1950'),
        ('core', '0007_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
    ]
