# Generated by Django 5.2 on 2025-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conceptmapresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='dndmatch',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='embed',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='likertscale',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='twine',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for completing the activity', null=True),
        ),
    ]
