# Generated by Django 5.1.6 on 2025-03-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250303_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_size',
            field=models.CharField(default='txt-base', max_length=1, verbose_name='text size preference'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=1, verbose_name='theme preference'),
        ),
    ]
