# Generated by Django 5.1.6 on 2025-03-20 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_text_size_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text="The user's score on this quiz", null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the quiz has been completed and submitted')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the user started the quiz')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed the quiz', null=True)),
                ('quiz', models.ForeignKey(help_text='The quiz that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='core.quiz')),
                ('user', models.ForeignKey(help_text='The user who submitted this quiz response', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quiz response',
                'verbose_name_plural': 'quiz responses',
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(help_text="The user's response data in JSON format")),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether this response is correct (null if not automatically gradable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='The question that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='core.question')),
                ('quiz_response', models.ForeignKey(help_text='The parent quiz response this question response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='core.userquizresponse')),
            ],
            options={
                'verbose_name': 'question response',
                'verbose_name_plural': 'question responses',
                'unique_together': {('quiz_response', 'question')},
            },
        ),
    ]
