# Generated by Django 5.1.6 on 2025-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_text_size_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speech_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='webSpeech speed'),
        ),
        migrations.AddField(
            model_name='user',
            name='speech_uri_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='webSpeech uri'),
        ),
    ]
