# Generated by Django 4.2.19 on 2025-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_text_size_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
