# Generated by Django 4.2.19 on 2025-03-26 01:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_responsedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsedata',
            name='data_reference_id',
            field=models.UUIDField(help_text='the id of the originating activity or survey', null=True),
        ),
        migrations.AddField(
            model_name='responsedata',
            name='data_type',
            field=models.TextField(help_text='Type for categorizing what data is what', null=True),
        ),
        migrations.AddField(
            model_name='responsedata',
            name='responses',
            field=models.JSONField(default=dict, help_text='Needs question id as well as response chosen and is correct flag'),
        ),
        migrations.AddField(
            model_name='responsedata',
            name='score',
            field=models.IntegerField(help_text='Score must be a non-negative integer', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='responsedata',
            name='time',
            field=models.TimeField(blank=True, help_text='Time taken during test', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facility_account',
            field=models.BooleanField(default=True, verbose_name='is facility account boolean'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsedata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False),
        ),
    ]
