# Generated by Django 5.1.6 on 2025-03-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userquestionresponse_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionresponse',
            name='question',
            field=models.OneToOneField(help_text='The question that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='core.question'),
        ),
        migrations.AlterField(
            model_name='userquestionresponse',
            name='quiz_response',
            field=models.OneToOneField(help_text='The parent quiz response', on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='core.userquizresponse'),
        ),
    ]
