# Generated by Django 5.1.6 on 2025-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userquestionresponse_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresponse',
            name='completion_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage completion of the lesson'),
        ),
    ]
