# Generated by Django 5.1.6 on 2025-03-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_text_size_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback_config',
            field=models.JSONField(blank=True, default=dict, help_text='Feedback configuration for this question, with options for correct/incorrect responses'),
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback provided for this response', null=True),
        ),
    ]
