# Generated by Django 4.2.19 on 2025-04-10 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_lesson_id_alter_poll_id_alter_pollquestion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPollResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('response_data', models.JSONField(default=list, help_text='list of responses from the poll')),
                ('time_spent', models.IntegerField(blank=True, help_text='The total time spent on this question', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='poll_lesson_origin', to='core.lesson')),
                ('poll', models.ForeignKey(help_text='The poll this poll question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='original_poll', to='core.poll')),
                ('user', models.ForeignKey(help_text='The user who submitted this poll response', on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPollQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='the uuid of the database item', primary_key=True, serialize=False)),
                ('response_data', models.JSONField(default=list, help_text='list of responses from the poll')),
                ('time_spent', models.IntegerField(blank=True, help_text='The total time spent on this question', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='poll_question_lesson_origin', to='core.lesson')),
                ('poll', models.ForeignKey(help_text='The poll this poll question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='poll_question_origin_poll', to='core.poll')),
                ('user', models.ForeignKey(help_text='The user who submitted this poll response', on_delete=django.db.models.deletion.CASCADE, related_name='poll_question_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
